### ISSUE TITLE
Enhancement: PDFExpense report looks ugly and hard to port for analytics use

### ISSUE THREAD

**Issue by aditikilledar** [aditikilledar/dollar_bot_SE23#22]
Enhance by creating ".csv" file of data in addition to ".pdf".
"csv" files are much easier to work with for analysis.
PDF File can also be beautified.

**Comment by shashank-madan** [comment]
Graphs generated in analytics can be extended and added to the pdf to give a more descriptive pdf report.

**Comment by shashank-madan** [comment]
PDF generated with all graphs from analytics to provide a comprehensive expense report rather than just a record of previous expenses.
Orientation of graphs and layouts can be beautified.
