### ISSUE TITLE
Docu Issue in: CONTRIBUTING.md to be updated

### ISSUE THREAD

**Issue by srina1h** [aditikilledar/dollar_bot_SE23#37]
Information in this file seems to reflect old authors, and outdated links. Need to update relevant links and details.

**Comment by srina1h** [comment]
@aditikilledar please take a look at this

**Comment by aditikilledar** [comment]
Oh I'd made a small typo for Fall '21. Fixed, made it Fall '23. Thanks for pointing it out.

**Comment by aditikilledar** [comment]
Please review and accept PR @srina1h and let me know if you have more inputs.
