### ISSUE TITLE
Docu missing: command instructions and docu missing

### ISSUE THREAD

**Issue by aditikilledar** [aditikilledar/dollar_bot_SE23#42]
in README.md, user has no idea what commands to run after getting app running. Need to add that.

**Comment by aditikilledar** [comment]
When you run your features and they work, take a quick screenshot and send it to me / upload to README.md functionalities section. Thanks @shashank-madan @srina1h

**Comment by shashank-madan** [comment]
Decided to take screenshots from video and update the docs
